In [4]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

In [5]:
import numpy as np
import tensorflow 
from tensorflow.keras.models import Sequential 
from tensorflow.keras import layers 
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.layers import Conv2D,MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [6]:
import keras
from keras.preprocessing.image import ImageDataGenerator

In [7]:
train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,rotation_range=180,zoom_range=0.2,horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

In [8]:
x_train=train_datagen.flow_from_directory(r'/content/drive/MyDrive/forest fire/Dataset/train_set',target_size = (64,64), batch_size = 32, class_mode = 'categorical')

Found 445 images belonging to 2 classes.


In [9]:
x_test=test_datagen.flow_from_directory(directory=r'/content/drive/MyDrive/forest fire/Dataset/test_set',target_size=(64,64),batch_size=32,class_mode='categorical')

Found 121 images belonging to 2 classes.


In [10]:
print(x_train.class_indices)#checking the number of classes

{'forest': 0, 'with fire': 1}


In [11]:
from collections import Counter as c
c(x_train.labels)

Counter({0: 281, 1: 164})

## Creating the model

In [12]:
model=Sequential()
model.add(Convolution2D(32,(3,3),input_shape=(64,64,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))                            
model.add(Flatten())
model.add(Dense(32))
model.add(Dense(2,activation='softmax'))

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 31, 32)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 30752)             0         
                                                                 
 dense (Dense)               (None, 32)                984096    
                                                                 
 dense_1 (Dense)             (None, 2)                 66        
                                                                 
Total params: 985,058
Trainable params: 985,058
Non-trainable params: 0
__________________________________________________

## ** Compiling the model**

In [14]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [15]:
len(x_train)

14

## **Fitting the model**

In [16]:
model.fit(x_train,steps_per_epoch=len(x_train),validation_data=x_test,validation_steps=len(x_test),epochs=10)

Epoch 1/10
14/14 [==============================] - 138s 10s/step - loss: 1.9883 - accuracy: 0.6584 - val_loss: 0.5860 - val_accuracy: 0.9339
Epoch 2/10
14/14 [==============================] - 21s 2s/step - loss: 0.3855 - accuracy: 0.8831 - val_loss: 0.1488 - val_accuracy: 0.9339
Epoch 3/10
14/14 [==============================] - 21s 2s/step - loss: 0.2278 - accuracy: 0.9101 - val_loss: 0.1112 - val_accuracy: 0.9587
Epoch 4/10
14/14 [==============================] - 21s 2s/step - loss: 0.2056 - accuracy: 0.9169 - val_loss: 0.0891 - val_accuracy: 0.9669
Epoch 5/10
14/14 [==============================] - 21s 1s/step - loss: 0.1958 - accuracy: 0.9124 - val_loss: 0.1257 - val_accuracy: 0.9339
Epoch 6/10
14/14 [==============================] - 21s 1s/step - loss: 0.2011 - accuracy: 0.8899 - val_loss: 0.1010 - val_accuracy: 0.9587
Epoch 7/10
14/14 [==============================] - 21s 2s/step - loss: 0.1768 - accuracy: 0.9213 - val_loss: 0.0729 - val_accuracy: 0.9917
Epoch 8/10
14/14 [

## **Saving our model**

In [17]:
model.save('forest1.h5')

## **Predicting our results**

In [18]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
model = load_model("forest1.h5")  

In [19]:
img = image.load_img(r"/content/drive/MyDrive/forest fire/Dataset/train_set/with fire/with fire (14).jpg",target_size= (64,64))#loading of the image
x = image.img_to_array(img)
x = np.expand_dims(x,axis = 0)#changing the shape
#pred = model.predict_classes(x)#predicting the classes
preds=model.predict(x)
preds=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 109ms/step


array([1])

In [20]:
index=['Forest','With Fire']
result = str(index[preds[0]])
result

'With Fire'

In [21]:
img = image.load_img(r"/content/drive/MyDrive/forest fire/Dataset/train_set/forest/with_fire (109).jpg",target_size= (64,64))#loading of the image
x = image.img_to_array(img)
x = np.expand_dims(x,axis = 0)
preds=model.predict(x)
preds=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 25ms/step


array([0])

In [22]:
index=['Forest','With Fire']
result=str(index[preds[0]])
result

'Forest'

In [23]:
img = image.load_img(r"/content/drive/MyDrive/forest fire/Dataset/test_set/with fire/Forest_Fire (4).jpg",target_size= (64,64))#loading of the image
x = image.img_to_array(img)
x = np.expand_dims(x,axis = 0)
preds=model.predict(x)
preds=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 23ms/step


array([1])

In [24]:
index=['Forest','With Fire']
result=str(index[preds[0]])
result

'With Fire'

In [25]:
img = image.load_img(r"/content/drive/MyDrive/forest fire/Dataset/test_set/forest/1009821.jpg",target_size= (64,64))#loading of the image
x = image.img_to_array(img)
x = np.expand_dims(x,axis = 0)
preds=model.predict(x)
preds=np.argmax(preds,axis=1)
preds

1/1 [==============================] - 0s 23ms/step


array([0])

In [26]:
index=['Forest','With Fire']
result=str(index[preds[0]])
result

'Forest'